/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.legislaturachaco.ft.ventanas;

/**
 *
 * @author Administrador
 */
public class ConfiguracionesVarias extends javax.swing.JPanel {

    /**
     * Creates new form ConfiguracionesVarias
     */
    public ConfiguracionesVarias() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tfCarpetaArchivos = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btGuardar = new javax.swing.JButton();
        btCangelar = new javax.swing.JButton();

        setLayout(new java.awt.GridLayout(1, 1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Carpeta de Archivos"));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.PAGE_AXIS));
        jPanel1.add(tfCarpetaArchivos);

        btGuardar.setText("Guardar");
        jPanel2.add(btGuardar);

        btCangelar.setText("Cancelar");
        jPanel2.add(btCangelar);

        jPanel1.add(jPanel2);

        add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCangelar;
    private javax.swing.JButton btGuardar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField tfCarpetaArchivos;
    // End of variables declaration//GEN-END:variables
}
